export const userActions = {
    /**============= FETCH INFO USER ============== */
    FETCH_INFO_USER: 'FETCH_INFO_USER',
    FETCH_INFO_USER_START: 'FETCH_INFO_USER_START',
    FETCH_INFO_USER_SUCCESS: 'FETCH_INFO_USER_SUCCESS',
    FETCH_INFO_USER_FAILED: 'FETCH_INFO_USER_FAILED',
    FETCH_INFO_USER_RESET: 'FETCH_INFO_USER_RESET',
    FETCH_INFO_USER_CLEAN: 'FETCH_INFO_USER_CLEAN',
};